services:
  analytics_processor:
    build: .
    restart: always
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioaccess
      MINIO_SECRET_KEY: miniosecret
      MINIO_BUCKET: messages
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker-1:9092
    networks:
      - kafka_dev_kafka_dev

networks:
  kafka_dev_kafka_dev:
    external: true
